### ISSUE TITLE
执行报错xpath解析错误

### ISSUE THREAD

**Issue by doling0** [lgxqf/UICrawler#27]
javax.xml.transform.TransformerException: 需要], 但找到: @
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.error(XPathParser.java:612)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.consumeExpected(XPathParser.java:530)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Predicate(XPathParser.java:1939)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1728)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1628)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1599)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1319)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Argument(XPathParser.java:1471)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.FunctionCall(XPathParser.java:1539)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PrimaryExpr(XPathParser.java:1448)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.FilterExpr(XPathParser.java:1347)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1280)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:842)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PredicateExpr(XPathParser.java:1956)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Predicate(XPathParser.java:1938)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1728)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1628)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1599)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1319)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(XPathParser.java:131)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:180)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:191)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:273)
        at util.XPathUtil.getNodesFromFile(XPathUtil.java:532)
        at Crawler.main(Crawler.java:487)
--------------- linked to ------------------
javax.xml.xpath.XPathExpressionException: javax.xml.transform.TransformerException: 需要], 但找到: @
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:287)
        at util.XPathUtil.getNodesFromFile(XPathUtil.java:532)
        at Crawler.main(Crawler.java:487)
Caused by: javax.xml.transform.TransformerException: 需要], 但找到: @
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.error(XPathParser.java:612)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.consumeExpected(XPathParser.java:530)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Predicate(XPathParser.java:1939)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1728)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1628)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1599)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1319)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Argument(XPathParser.java:1471)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.FunctionCall(XPathParser.java:1539)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PrimaryExpr(XPathParser.java:1448)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.FilterExpr(XPathParser.java:1347)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1280)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:842)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PredicateExpr(XPathParser.java:1956)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Predicate(XPathParser.java:1938)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Step(XPathParser.java:1728)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelativeLocationPath(XPathParser.java:1628)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.LocationPath(XPathParser.java:1599)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.PathExpr(XPathParser.java:1319)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnionExpr(XPathParser.java:1238)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.UnaryExpr(XPathParser.java:1144)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.MultiplicativeExpr(XPathParser.java:1065)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AdditiveExpr(XPathParser.java:1007)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.RelationalExpr(XPathParser.java:932)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.EqualityExpr(XPathParser.java:872)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.AndExpr(XPathParser.java:836)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.OrExpr(XPathParser.java:809)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.Expr(XPathParser.java:792)
        at com.sun.org.apache.xpath.internal.compiler.XPathParser.initXPath(XPathParser.java:131)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:180)
        at com.sun.org.apache.xpath.internal.XPath.<init>(XPath.java:268)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.eval(XPathImpl.java:191)
        at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:273)
        ... 2 more
16:33:56.024 [main] ERROR Crawler - ------------------------------ERROR. Testing stopped unexpectedly!!!!----------------

**Comment by doling0** [comment]
手动捂脸。。。配错了 ANDROID_BOTTOM_TAB_BAR_ID
